/**
 * 精选字体清单：离线兜底与推荐位的数据源，基础字段取自 fontsource API
 * （https://api.fontsource.org/v1/fonts，2026-08-29 核对）；version 取 jsDelivr
 * 包元数据的 latest 标签，2026-08-31 核对。chiron-sung-hk 没有 npm 包，镜像回落 latest。
 * 中文部分覆盖 Google Fonts 上全部带 chinese-* subset 的字体，
 * 目录接口拉不到时 fetchCatalog 直接回落到这里。
 */

import type { FontEntry } from './catalog'

export const CURATED_FONTS: FontEntry[] = [
  {
    id: 'noto-sans-sc',
    version: '5.3.0',
    family: 'Noto Sans SC',
    category: 'sans-serif',
    subsets: ['chinese-simplified', 'cyrillic', 'latin', 'latin-ext', 'vietnamese'],
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    cjk: 'sc',
  },
  {
    id: 'noto-serif-sc',
    version: '5.3.0',
    family: 'Noto Serif SC',
    category: 'serif',
    subsets: ['chinese-simplified', 'cyrillic', 'latin', 'latin-ext', 'vietnamese'],
    weights: [200, 300, 400, 500, 600, 700, 800, 900],
    cjk: 'sc',
  },
  {
    id: 'liu-jian-mao-cao',
    version: '5.3.0',
    family: 'Liu Jian Mao Cao',
    category: 'handwriting',
    subsets: ['chinese-simplified', 'latin'],
    weights: [400],
    cjk: 'sc',
  },
  {
    id: 'long-cang',
    version: '5.3.0',
    family: 'Long Cang',
    category: 'handwriting',
    subsets: ['chinese-simplified', 'latin'],
    weights: [400],
    cjk: 'sc',
  },
  {
    id: 'ma-shan-zheng',
    version: '5.3.1',
    family: 'Ma Shan Zheng',
    category: 'handwriting',
    subsets: ['chinese-simplified', 'latin'],
    weights: [400],
    cjk: 'sc',
  },
  {
    id: 'wdxl-lubrifont-sc',
    version: '5.3.0',
    family: 'WDXL Lubrifont SC',
    category: 'sans-serif',
    subsets: ['chinese-simplified', 'cyrillic', 'latin', 'latin-ext', 'symbols2'],
    weights: [400],
    cjk: 'sc',
  },
  {
    id: 'zcool-kuaile',
    version: '5.3.0',
    family: 'ZCOOL KuaiLe',
    category: 'sans-serif',
    subsets: ['chinese-simplified', 'latin'],
    weights: [400],
    cjk: 'sc',
  },
  {
    id: 'zcool-qingke-huangyou',
    version: '5.3.0',
    family: 'ZCOOL QingKe HuangYou',
    category: 'sans-serif',
    subsets: ['chinese-simplified', 'latin'],
    weights: [400],
    cjk: 'sc',
  },
  {
    id: 'zcool-xiaowei',
    version: '5.3.0',
    family: 'ZCOOL XiaoWei',
    category: 'sans-serif',
    subsets: ['chinese-simplified', 'latin'],
    weights: [400],
    cjk: 'sc',
  },
  {
    id: 'zhi-mang-xing',
    version: '5.3.0',
    family: 'Zhi Mang Xing',
    category: 'handwriting',
    subsets: ['chinese-simplified', 'latin'],
    weights: [400],
    cjk: 'sc',
  },
  {
    id: 'noto-sans-tc',
    version: '5.3.0',
    family: 'Noto Sans TC',
    category: 'sans-serif',
    subsets: ['chinese-traditional', 'cyrillic', 'latin', 'latin-ext', 'vietnamese'],
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    cjk: 'tc',
  },
  {
    id: 'noto-serif-tc',
    version: '5.3.0',
    family: 'Noto Serif TC',
    category: 'serif',
    subsets: ['chinese-traditional', 'cyrillic', 'latin', 'latin-ext', 'vietnamese'],
    weights: [200, 300, 400, 500, 600, 700, 800, 900],
    cjk: 'tc',
  },
  {
    id: 'bpmf-huninn',
    version: '5.3.0',
    family: 'Bpmf Huninn',
    category: 'sans-serif',
    subsets: ['chinese-traditional', 'latin', 'latin-ext'],
    weights: [400],
    cjk: 'tc',
  },
  {
    id: 'bpmf-iansui',
    version: '5.3.0',
    family: 'Bpmf Iansui',
    category: 'handwriting',
    subsets: ['chinese-traditional', 'latin', 'latin-ext'],
    weights: [400],
    cjk: 'tc',
  },
  {
    id: 'bpmf-zihi-kai-std',
    version: '5.3.0',
    family: 'Bpmf Zihi Kai Std',
    category: 'sans-serif',
    subsets: ['chinese-traditional', 'latin', 'latin-ext'],
    weights: [400],
    cjk: 'tc',
  },
  {
    id: 'cactus-classical-serif',
    version: '5.3.0',
    family: 'Cactus Classical Serif',
    category: 'serif',
    subsets: ['chinese-traditional', 'cyrillic', 'latin', 'latin-ext', 'vietnamese'],
    weights: [400],
    cjk: 'tc',
  },
  {
    id: 'chiron-goround-tc',
    version: '5.3.0',
    family: 'Chiron GoRound TC',
    category: 'sans-serif',
    subsets: [
      'chinese-traditional',
      'cyrillic',
      'cyrillic-ext',
      'latin',
      'latin-ext',
      'vietnamese',
    ],
    weights: [200, 300, 400, 500, 600, 700, 800, 900],
    cjk: 'tc',
  },
  {
    id: 'chiron-hei-hk',
    version: '5.3.1',
    family: 'Chiron Hei HK',
    category: 'sans-serif',
    subsets: [
      'chinese-traditional',
      'cyrillic',
      'cyrillic-ext',
      'greek',
      'greek-ext',
      'latin',
      'latin-ext',
      'symbols2',
      'vietnamese',
    ],
    weights: [200, 300, 400, 500, 600, 700, 800, 900],
    cjk: 'tc',
  },
  {
    id: 'chocolate-classical-sans',
    version: '5.3.0',
    family: 'Chocolate Classical Sans',
    category: 'sans-serif',
    subsets: ['chinese-traditional', 'cyrillic', 'latin', 'latin-ext', 'vietnamese'],
    weights: [400],
    cjk: 'tc',
  },
  {
    id: 'huninn',
    version: '5.3.0',
    family: 'Huninn',
    category: 'sans-serif',
    subsets: ['chinese-traditional', 'cyrillic', 'latin', 'latin-ext', 'vietnamese'],
    weights: [400],
    cjk: 'tc',
  },
  {
    id: 'iansui',
    version: '5.3.0',
    family: 'Iansui',
    category: 'handwriting',
    subsets: ['chinese-traditional', 'latin', 'latin-ext', 'symbols2'],
    weights: [400],
    cjk: 'tc',
  },
  {
    id: 'lxgw-marker-gothic',
    version: '5.3.0',
    family: 'LXGW Marker Gothic',
    category: 'sans-serif',
    subsets: [
      'chinese-traditional',
      'cyrillic',
      'cyrillic-ext',
      'greek',
      'latin',
      'latin-ext',
      'symbols2',
      'vietnamese',
    ],
    weights: [400],
    cjk: 'tc',
  },
  {
    id: 'lxgw-wenkai-mono-tc',
    version: '5.3.0',
    family: 'LXGW WenKai Mono TC',
    category: 'monospace',
    subsets: [
      'chinese-traditional',
      'cyrillic',
      'cyrillic-ext',
      'greek',
      'greek-ext',
      'latin',
      'latin-ext',
      'lisu',
      'vietnamese',
    ],
    weights: [300, 400, 700],
    cjk: 'tc',
  },
  {
    id: 'lxgw-wenkai-tc',
    version: '5.3.0',
    family: 'LXGW WenKai TC',
    category: 'handwriting',
    subsets: [
      'chinese-traditional',
      'cyrillic',
      'cyrillic-ext',
      'greek',
      'greek-ext',
      'latin',
      'latin-ext',
      'lisu',
      'vietnamese',
    ],
    weights: [300, 400, 700],
    cjk: 'tc',
  },
  {
    id: 'uoqmunthenkhung',
    version: '5.3.0',
    family: 'UoqMunThenKhung',
    category: 'serif',
    subsets: ['chinese-traditional', 'cyrillic', 'latin', 'symbols2'],
    weights: [400],
    cjk: 'tc',
  },
  {
    id: 'wdxl-lubrifont-tc',
    version: '5.3.0',
    family: 'WDXL Lubrifont TC',
    category: 'sans-serif',
    subsets: ['chinese-traditional', 'cyrillic', 'latin', 'latin-ext', 'symbols2'],
    weights: [400],
    cjk: 'tc',
  },
  {
    id: 'noto-sans-hk',
    version: '5.3.0',
    family: 'Noto Sans HK',
    category: 'sans-serif',
    subsets: ['chinese-hongkong', 'cyrillic', 'latin', 'latin-ext', 'vietnamese'],
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    cjk: 'hk',
  },
  {
    id: 'noto-serif-hk',
    version: '5.3.0',
    family: 'Noto Serif HK',
    category: 'serif',
    subsets: ['chinese-hongkong', 'cyrillic', 'latin', 'latin-ext', 'vietnamese'],
    weights: [200, 300, 400, 500, 600, 700, 800, 900],
    cjk: 'hk',
  },
  {
    id: 'chiron-sung-hk',
    family: 'Chiron Sung HK',
    category: 'serif',
    subsets: [
      'chinese-hongkong',
      'cyrillic',
      'cyrillic-ext',
      'greek',
      'latin',
      'latin-ext',
      'symbols2',
      'vietnamese',
    ],
    weights: [200, 300, 400, 500, 600, 700, 800, 900],
    cjk: 'hk',
  },

  {
    id: 'noto-sans-jp',
    version: '5.3.0',
    family: 'Noto Sans JP',
    category: 'sans-serif',
    subsets: ['cyrillic', 'japanese', 'latin', 'latin-ext', 'vietnamese'],
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    cjk: 'jp',
  },
  {
    id: 'noto-serif-jp',
    version: '5.3.0',
    family: 'Noto Serif JP',
    category: 'serif',
    subsets: ['cyrillic', 'japanese', 'latin', 'latin-ext', 'vietnamese'],
    weights: [200, 300, 400, 500, 600, 700, 800, 900],
    cjk: 'jp',
  },
  {
    id: 'm-plus-rounded-1c',
    version: '5.3.0',
    family: 'M PLUS Rounded 1c',
    category: 'sans-serif',
    subsets: [
      'cyrillic',
      'cyrillic-ext',
      'greek',
      'greek-ext',
      'hebrew',
      'japanese',
      'latin',
      'latin-ext',
      'vietnamese',
    ],
    weights: [100, 300, 400, 500, 700, 800, 900],
    cjk: 'jp',
  },
  {
    id: 'zen-maru-gothic',
    version: '5.3.0',
    family: 'Zen Maru Gothic',
    category: 'sans-serif',
    subsets: ['cyrillic', 'greek', 'japanese', 'latin', 'latin-ext'],
    weights: [300, 400, 500, 700, 900],
    cjk: 'jp',
  },
  {
    id: 'dela-gothic-one',
    version: '5.3.0',
    family: 'Dela Gothic One',
    category: 'display',
    subsets: ['cyrillic', 'greek', 'japanese', 'latin', 'latin-ext', 'vietnamese'],
    weights: [400],
    cjk: 'jp',
  },
  {
    id: 'shippori-mincho',
    version: '5.3.0',
    family: 'Shippori Mincho',
    category: 'serif',
    subsets: ['japanese', 'latin', 'latin-ext'],
    weights: [400, 500, 600, 700, 800],
    cjk: 'jp',
  },
  {
    id: 'kosugi-maru',
    version: '5.3.0',
    family: 'Kosugi Maru',
    category: 'sans-serif',
    subsets: ['cyrillic', 'japanese', 'latin', 'latin-ext'],
    weights: [400],
    cjk: 'jp',
  },
  {
    id: 'rampart-one',
    version: '5.3.0',
    family: 'Rampart One',
    category: 'display',
    subsets: ['cyrillic', 'japanese', 'latin', 'latin-ext'],
    weights: [400],
    cjk: 'jp',
  },
  {
    id: 'yuji-syuku',
    version: '5.3.0',
    family: 'Yuji Syuku',
    category: 'serif',
    subsets: ['cyrillic', 'japanese', 'latin', 'latin-ext'],
    weights: [400],
    cjk: 'jp',
  },
  {
    id: 'hachi-maru-pop',
    version: '5.3.0',
    family: 'Hachi Maru Pop',
    category: 'handwriting',
    subsets: ['cyrillic', 'japanese', 'latin', 'latin-ext'],
    weights: [400],
    cjk: 'jp',
  },

  {
    id: 'noto-sans-kr',
    version: '5.3.0',
    family: 'Noto Sans KR',
    category: 'sans-serif',
    subsets: ['cyrillic', 'korean', 'latin', 'latin-ext', 'vietnamese'],
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    cjk: 'kr',
  },
  {
    id: 'noto-serif-kr',
    version: '5.3.0',
    family: 'Noto Serif KR',
    category: 'serif',
    subsets: ['cyrillic', 'korean', 'latin', 'latin-ext', 'vietnamese'],
    weights: [200, 300, 400, 500, 600, 700, 800, 900],
    cjk: 'kr',
  },
  {
    id: 'black-han-sans',
    version: '5.3.0',
    family: 'Black Han Sans',
    category: 'sans-serif',
    subsets: ['korean', 'latin'],
    weights: [400],
    cjk: 'kr',
  },
  {
    id: 'do-hyeon',
    version: '5.3.0',
    family: 'Do Hyeon',
    category: 'sans-serif',
    subsets: ['korean', 'latin'],
    weights: [400],
    cjk: 'kr',
  },
  {
    id: 'jua',
    version: '5.3.0',
    family: 'Jua',
    category: 'sans-serif',
    subsets: ['korean', 'latin'],
    weights: [400],
    cjk: 'kr',
  },
  {
    id: 'gowun-dodum',
    version: '5.3.0',
    family: 'Gowun Dodum',
    category: 'sans-serif',
    subsets: ['korean', 'latin', 'latin-ext', 'vietnamese'],
    weights: [400],
    cjk: 'kr',
  },
  {
    id: 'nanum-myeongjo',
    version: '5.3.0',
    family: 'Nanum Myeongjo',
    category: 'serif',
    subsets: ['korean', 'latin'],
    weights: [400, 700, 800],
    cjk: 'kr',
  },
  {
    id: 'gasoek-one',
    version: '5.3.0',
    family: 'Gasoek One',
    category: 'sans-serif',
    subsets: ['korean', 'latin', 'latin-ext'],
    weights: [400],
    cjk: 'kr',
  },

  {
    id: 'inter',
    version: '5.3.0',
    family: 'Inter',
    category: 'sans-serif',
    subsets: ['cyrillic', 'cyrillic-ext', 'greek', 'greek-ext', 'latin', 'latin-ext', 'vietnamese'],
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
  },
  {
    id: 'poppins',
    version: '5.3.0',
    family: 'Poppins',
    category: 'sans-serif',
    subsets: ['devanagari', 'latin', 'latin-ext'],
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
  },
  {
    id: 'montserrat',
    version: '5.3.0',
    family: 'Montserrat',
    category: 'sans-serif',
    subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext', 'vietnamese'],
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
  },
  {
    id: 'rubik',
    version: '5.3.0',
    family: 'Rubik',
    category: 'sans-serif',
    subsets: ['arabic', 'cyrillic', 'cyrillic-ext', 'hebrew', 'latin', 'latin-ext'],
    weights: [300, 400, 500, 600, 700, 800, 900],
  },
  {
    id: 'nunito',
    version: '5.3.0',
    family: 'Nunito',
    category: 'sans-serif',
    subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext', 'vietnamese'],
    weights: [200, 300, 400, 500, 600, 700, 800, 900],
  },
  {
    id: 'outfit',
    version: '5.3.0',
    family: 'Outfit',
    category: 'sans-serif',
    subsets: ['latin', 'latin-ext'],
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
  },
  {
    id: 'sora',
    version: '5.3.0',
    family: 'Sora',
    category: 'sans-serif',
    subsets: ['latin', 'latin-ext'],
    weights: [100, 200, 300, 400, 500, 600, 700, 800],
  },
  {
    id: 'syne',
    version: '5.3.0',
    family: 'Syne',
    category: 'sans-serif',
    subsets: ['greek', 'latin', 'latin-ext'],
    weights: [400, 500, 600, 700, 800],
  },
  {
    id: 'space-grotesk',
    version: '5.3.0',
    family: 'Space Grotesk',
    category: 'sans-serif',
    subsets: ['latin', 'latin-ext', 'vietnamese'],
    weights: [300, 400, 500, 600, 700],
  },
  {
    id: 'oswald',
    version: '5.3.0',
    family: 'Oswald',
    category: 'sans-serif',
    subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext', 'vietnamese'],
    weights: [200, 300, 400, 500, 600, 700],
  },
  {
    id: 'archivo-black',
    version: '5.3.0',
    family: 'Archivo Black',
    category: 'sans-serif',
    subsets: ['latin', 'latin-ext'],
    weights: [400],
  },
  {
    id: 'bebas-neue',
    version: '5.3.0',
    family: 'Bebas Neue',
    category: 'sans-serif',
    subsets: ['latin', 'latin-ext'],
    weights: [400],
  },
  {
    id: 'fredoka',
    version: '5.3.0',
    family: 'Fredoka',
    category: 'sans-serif',
    subsets: ['hebrew', 'latin', 'latin-ext'],
    weights: [300, 400, 500, 600, 700],
  },
  {
    id: 'righteous',
    version: '5.3.0',
    family: 'Righteous',
    category: 'display',
    subsets: ['latin', 'latin-ext'],
    weights: [400],
  },
  {
    id: 'playfair-display',
    version: '5.3.0',
    family: 'Playfair Display',
    category: 'serif',
    subsets: ['cyrillic', 'latin', 'latin-ext', 'vietnamese'],
    weights: [400, 500, 600, 700, 800, 900],
  },
  {
    id: 'dm-serif-display',
    version: '5.3.0',
    family: 'DM Serif Display',
    category: 'serif',
    subsets: ['latin', 'latin-ext'],
    weights: [400],
  },
  {
    id: 'abril-fatface',
    version: '5.3.0',
    family: 'Abril Fatface',
    category: 'display',
    subsets: ['latin', 'latin-ext'],
    weights: [400],
  },
  {
    id: 'bungee',
    version: '5.3.0',
    family: 'Bungee',
    category: 'display',
    subsets: ['latin', 'latin-ext', 'vietnamese'],
    weights: [400],
  },
  {
    id: 'lobster',
    version: '5.3.0',
    family: 'Lobster',
    category: 'display',
    subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext', 'vietnamese'],
    weights: [400],
  },
  {
    id: 'pacifico',
    version: '5.3.0',
    family: 'Pacifico',
    category: 'handwriting',
    subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext', 'vietnamese'],
    weights: [400],
  },
]

const BY_ID = new Map(CURATED_FONTS.map((f) => [f.id, f]))
const BY_FAMILY = new Map(CURATED_FONTS.map((f) => [f.family.toLowerCase(), f]))

export function getCuratedById(id: string): FontEntry | undefined {
  return BY_ID.get(id)
}

/** 配置里存的是 family 而非 id，按 family 反查是加载链路的主入口。 */
export function getCuratedByFamily(family: string): FontEntry | undefined {
  return BY_FAMILY.get(family.trim().toLowerCase())
}
