/** 精选图标的中英文关键词与类目。全量索引只按英文名搜索，这一层负责可发现性。 */
export type CuratedIconCategory =
  | 'common'
  | 'people'
  | 'business'
  | 'tech'
  | 'nature'
  | 'travel'
  | 'food'
  | 'media'
  | 'objects'
  | 'symbols'

export const CURATED_ICON_CATEGORIES: readonly CuratedIconCategory[] = [
  'common',
  'people',
  'business',
  'tech',
  'nature',
  'travel',
  'food',
  'media',
  'objects',
  'symbols',
]

export interface CuratedIcon {
  name: string
  zh: string
  en: string
  category: CuratedIconCategory
}

export const CURATED_ICONS: readonly CuratedIcon[] = [
  { name: 'tree-palm', zh: '棕榈树', en: 'palm tree', category: 'nature' },
  { name: 'badge-check', zh: '认证', en: 'verified', category: 'common' },
  { name: 'sparkles', zh: '闪光', en: 'sparkles', category: 'common' },
  { name: 'star', zh: '星形', en: 'star', category: 'common' },
  { name: 'heart', zh: '心形', en: 'heart', category: 'common' },
  { name: 'flag', zh: '旗帜', en: 'flag', category: 'common' },
  { name: 'award', zh: '奖牌', en: 'award', category: 'common' },
  { name: 'trophy', zh: '奖杯', en: 'trophy', category: 'common' },
  { name: 'gift', zh: '礼物', en: 'gift', category: 'common' },
  { name: 'bell', zh: '铃铛', en: 'bell', category: 'common' },
  { name: 'bookmark', zh: '书签', en: 'bookmark', category: 'common' },
  { name: 'pin', zh: '图钉', en: 'pin', category: 'common' },
  { name: 'tag', zh: '标签', en: 'tag', category: 'common' },
  { name: 'link', zh: '链接', en: 'link', category: 'common' },
  { name: 'search', zh: '搜索', en: 'search', category: 'common' },
  { name: 'settings', zh: '设置', en: 'settings', category: 'common' },
  { name: 'sliders-horizontal', zh: '参数', en: 'sliders', category: 'common' },
  { name: 'funnel', zh: '筛选', en: 'filter', category: 'common' },
  { name: 'shuffle', zh: '随机', en: 'shuffle', category: 'common' },
  { name: 'refresh-cw', zh: '刷新', en: 'refresh', category: 'common' },
  { name: 'user', zh: '用户', en: 'user', category: 'people' },
  { name: 'users', zh: '团队', en: 'users', category: 'people' },
  { name: 'user-round', zh: '成员', en: 'member', category: 'people' },
  { name: 'contact', zh: '联系人', en: 'contact', category: 'people' },
  { name: 'hand', zh: '手掌', en: 'hand', category: 'people' },
  { name: 'thumbs-up', zh: '点赞', en: 'thumbs up', category: 'people' },
  { name: 'face-slightly-smiling', zh: '笑脸', en: 'smile', category: 'people' },
  { name: 'face-grinning', zh: '大笑', en: 'laugh', category: 'people' },
  { name: 'party-popper', zh: '庆祝', en: 'celebration', category: 'people' },
  { name: 'graduation-cap', zh: '毕业', en: 'graduation', category: 'people' },
  { name: 'briefcase', zh: '公文包', en: 'briefcase', category: 'business' },
  { name: 'building', zh: '公司', en: 'building', category: 'business' },
  { name: 'building-2', zh: '机构', en: 'institution', category: 'business' },
  { name: 'factory', zh: '工厂', en: 'factory', category: 'business' },
  { name: 'store', zh: '商店', en: 'store', category: 'business' },
  { name: 'shopping-cart', zh: '购物车', en: 'cart', category: 'business' },
  { name: 'credit-card', zh: '支付', en: 'payment', category: 'business' },
  { name: 'wallet', zh: '钱包', en: 'wallet', category: 'business' },
  { name: 'receipt', zh: '收据', en: 'receipt', category: 'business' },
  { name: 'chart-line', zh: '折线图', en: 'line chart', category: 'business' },
  { name: 'chart-bar', zh: '柱状图', en: 'bar chart', category: 'business' },
  { name: 'chart-pie', zh: '饼图', en: 'pie chart', category: 'business' },
  { name: 'trending-up', zh: '增长', en: 'growth', category: 'business' },
  { name: 'target', zh: '目标', en: 'target', category: 'business' },
  { name: 'lightbulb', zh: '创意', en: 'idea', category: 'business' },
  { name: 'rocket', zh: '火箭', en: 'rocket', category: 'tech' },
  { name: 'cpu', zh: '芯片', en: 'cpu', category: 'tech' },
  { name: 'memory-stick', zh: '内存', en: 'memory', category: 'tech' },
  { name: 'server', zh: '服务器', en: 'server', category: 'tech' },
  { name: 'database', zh: '数据库', en: 'database', category: 'tech' },
  { name: 'cloud', zh: '云', en: 'cloud', category: 'tech' },
  { name: 'cloud-upload', zh: '上传', en: 'upload', category: 'tech' },
  { name: 'cloud-download', zh: '下载', en: 'download', category: 'tech' },
  { name: 'wifi', zh: '网络', en: 'wifi', category: 'tech' },
  { name: 'bluetooth', zh: '蓝牙', en: 'bluetooth', category: 'tech' },
  { name: 'plug', zh: '电源', en: 'plug', category: 'tech' },
  { name: 'battery-charging', zh: '充电', en: 'charging', category: 'tech' },
  { name: 'terminal', zh: '终端', en: 'terminal', category: 'tech' },
  { name: 'code-xml', zh: '代码', en: 'code', category: 'tech' },
  { name: 'git-branch', zh: '分支', en: 'branch', category: 'tech' },
  { name: 'bug', zh: '缺陷', en: 'bug', category: 'tech' },
  { name: 'shield', zh: '安全', en: 'shield', category: 'tech' },
  { name: 'lock', zh: '锁', en: 'lock', category: 'tech' },
  { name: 'key', zh: '钥匙', en: 'key', category: 'tech' },
  { name: 'fingerprint-pattern', zh: '指纹', en: 'fingerprint-pattern', category: 'tech' },
  { name: 'eye', zh: '眼睛', en: 'eye', category: 'tech' },
  { name: 'scan-face', zh: '人脸识别', en: 'face scan', category: 'tech' },
  { name: 'bot', zh: '机器人', en: 'bot', category: 'tech' },
  { name: 'brain', zh: '大脑', en: 'brain', category: 'tech' },
  { name: 'sun', zh: '太阳', en: 'sun', category: 'nature' },
  { name: 'moon', zh: '月亮', en: 'moon', category: 'nature' },
  { name: 'cloud-sun', zh: '晴天', en: 'sunny', category: 'nature' },
  { name: 'cloud-rain', zh: '下雨', en: 'rain', category: 'nature' },
  { name: 'cloud-snow', zh: '下雪', en: 'snow', category: 'nature' },
  { name: 'zap', zh: '闪电', en: 'lightning', category: 'nature' },
  { name: 'rainbow', zh: '彩虹', en: 'rainbow', category: 'nature' },
  { name: 'flower', zh: '花朵', en: 'flower', category: 'nature' },
  { name: 'leaf', zh: '叶子', en: 'leaf', category: 'nature' },
  { name: 'trees', zh: '树林', en: 'trees', category: 'nature' },
  { name: 'sprout', zh: '发芽', en: 'sprout', category: 'nature' },
  { name: 'mountain', zh: '山', en: 'mountain', category: 'nature' },
  { name: 'map', zh: '地图', en: 'map', category: 'travel' },
  { name: 'compass', zh: '指南针', en: 'compass', category: 'travel' },
  { name: 'globe', zh: '地球', en: 'globe', category: 'travel' },
  { name: 'plane', zh: '飞机', en: 'plane', category: 'travel' },
  { name: 'car', zh: '汽车', en: 'car', category: 'travel' },
  { name: 'train-front', zh: '火车', en: 'train', category: 'travel' },
  { name: 'ship', zh: '轮船', en: 'ship', category: 'travel' },
  { name: 'bike', zh: '自行车', en: 'bike', category: 'travel' },
  { name: 'house', zh: '家', en: 'home', category: 'travel' },
  { name: 'tent', zh: '露营', en: 'camping', category: 'travel' },
  { name: 'camera', zh: '相机', en: 'camera', category: 'media' },
  { name: 'image', zh: '图片', en: 'image', category: 'media' },
  { name: 'film', zh: '胶片', en: 'film', category: 'media' },
  { name: 'video', zh: '视频', en: 'video', category: 'media' },
  { name: 'music', zh: '音乐', en: 'music', category: 'media' },
  { name: 'headphones', zh: '耳机', en: 'headphones', category: 'media' },
  { name: 'mic', zh: '麦克风', en: 'microphone', category: 'media' },
  { name: 'radio', zh: '广播', en: 'radio', category: 'media' },
  { name: 'mic-signal', zh: '播客', en: 'podcast', category: 'media' },
  { name: 'book-open', zh: '阅读', en: 'reading', category: 'media' },
  { name: 'newspaper', zh: '新闻', en: 'news', category: 'media' },
  { name: 'pen-line', zh: '写作', en: 'writing', category: 'media' },
  { name: 'palette', zh: '调色板', en: 'palette', category: 'media' },
  { name: 'brush', zh: '画笔', en: 'brush', category: 'media' },
  { name: 'coffee', zh: '咖啡', en: 'coffee', category: 'food' },
  { name: 'cup-soda', zh: '饮料', en: 'drink', category: 'food' },
  { name: 'beer', zh: '啤酒', en: 'beer', category: 'food' },
  { name: 'wine', zh: '红酒', en: 'wine', category: 'food' },
  { name: 'utensils', zh: '餐具', en: 'dining', category: 'food' },
  { name: 'pizza', zh: '披萨', en: 'pizza', category: 'food' },
  { name: 'cake', zh: '蛋糕', en: 'cake', category: 'food' },
  { name: 'ice-cream-cone', zh: '冰淇淋', en: 'ice cream', category: 'food' },
  { name: 'apple', zh: '苹果', en: 'apple', category: 'food' },
  { name: 'citrus', zh: '柑橘', en: 'citrus', category: 'food' },
  { name: 'banana', zh: '香蕉', en: 'banana', category: 'food' },
  { name: 'grape', zh: '葡萄', en: 'grape', category: 'food' },
  { name: 'message-circle', zh: '聊天', en: 'chat', category: 'objects' },
  { name: 'send', zh: '发送', en: 'send', category: 'objects' },
  { name: 'mail', zh: '邮件', en: 'mail', category: 'objects' },
  { name: 'phone', zh: '电话', en: 'phone', category: 'objects' },
  { name: 'calendar', zh: '日历', en: 'calendar', category: 'objects' },
  { name: 'clock', zh: '时钟', en: 'clock', category: 'objects' },
  { name: 'timer', zh: '计时', en: 'timer', category: 'objects' },
  { name: 'alarm-clock', zh: '闹钟', en: 'alarm', category: 'objects' },
  { name: 'folder', zh: '文件夹', en: 'folder', category: 'objects' },
  { name: 'file-text', zh: '文档', en: 'document', category: 'objects' },
  { name: 'clipboard-list', zh: '清单', en: 'checklist', category: 'objects' },
  { name: 'notebook-pen', zh: '笔记', en: 'notebook', category: 'objects' },
  { name: 'printer', zh: '打印机', en: 'printer', category: 'objects' },
  { name: 'scissors', zh: '剪刀', en: 'scissors', category: 'objects' },
  { name: 'package', zh: '包裹', en: 'package', category: 'objects' },
  { name: 'box', zh: '箱子', en: 'box', category: 'objects' },
  { name: 'wrench', zh: '工具', en: 'wrench', category: 'objects' },
  { name: 'hammer', zh: '锤子', en: 'hammer', category: 'objects' },
  { name: 'ruler', zh: '尺子', en: 'ruler', category: 'objects' },
  { name: 'puzzle', zh: '拼图', en: 'puzzle', category: 'symbols' },
  { name: 'infinity', zh: '无穷', en: 'infinity', category: 'symbols' },
  { name: 'check', zh: '对勾', en: 'check', category: 'symbols' },
  { name: 'x', zh: '叉号', en: 'close', category: 'symbols' },
  { name: 'plus', zh: '加号', en: 'plus', category: 'symbols' },
  { name: 'minus', zh: '减号', en: 'minus', category: 'symbols' },
  { name: 'equal', zh: '等号', en: 'equal', category: 'symbols' },
  { name: 'divide', zh: '除号', en: 'divide', category: 'symbols' },
  { name: 'percent', zh: '百分比', en: 'percent', category: 'symbols' },
  { name: 'hash', zh: '井号', en: 'hash', category: 'symbols' },
  { name: 'at-sign', zh: '艾特', en: 'at sign', category: 'symbols' },
  { name: 'circle-question-mark', zh: '问号', en: 'circle-question-mark', category: 'symbols' },
  { name: 'triangle-alert', zh: '叹号', en: 'exclamation', category: 'symbols' },
  { name: 'info', zh: '信息', en: 'info', category: 'symbols' },
  { name: 'ban', zh: '禁止', en: 'ban', category: 'symbols' },
  { name: 'badge-question-mark', zh: '帮助', en: 'help', category: 'symbols' },
  { name: 'shield-alert', zh: '警告', en: 'alert', category: 'symbols' },
  { name: 'languages', zh: '语言', en: 'languages', category: 'symbols' },
  { name: 'type', zh: '字体', en: 'type', category: 'symbols' },
  { name: 'bold', zh: '加粗', en: 'bold', category: 'symbols' },
  { name: 'italic', zh: '斜体', en: 'italic', category: 'symbols' },
  { name: 'underline', zh: '下划线', en: 'underline', category: 'symbols' },
  { name: 'text-align-start', zh: '左对齐', en: 'align left', category: 'symbols' },
  { name: 'text-align-center', zh: '居中', en: 'align center', category: 'symbols' },
  { name: 'text-align-end', zh: '右对齐', en: 'align right', category: 'symbols' },
  { name: 'list', zh: '列表', en: 'list', category: 'symbols' },
]
